### ISSUE TITLE
ImportError: No module named zipp 

### ISSUE THREAD

**Issue by RaviTezu** [StackStorm/st2vagrantdev#3]
Executing `make requirements` inside ~/st2 in the vagrant vm is failing with the below error: 
```
vagrant@ubuntu-xenial:~/st2$ make requirements

==================== virtualenv ====================

# Note: We pass --no-download flag to make sure version of pip which we install (9.0.1) is used
# instead of latest version being downloaded from PyPi
test -f virtualenv/bin/activate || virtualenv --python=python2.7 virtualenv --no-download
Traceback (most recent call last):
  File "/home/vagrant/.local/bin/virtualenv", line 7, in <module>
    from virtualenv.__main__ import run_with_catch
  File "/home/vagrant/.local/lib/python2.7/site-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run
  File "/home/vagrant/.local/lib/python2.7/site-packages/virtualenv/run/__init__.py", line 12, in <module>
    from .plugin.activators import ActivationSelector
  File "/home/vagrant/.local/lib/python2.7/site-packages/virtualenv/run/plugin/activators.py", line 6, in <module>
    from .base import ComponentBuilder
  File "/home/vagrant/.local/lib/python2.7/site-packages/virtualenv/run/plugin/base.py", line 9, in <module>
    from importlib_metadata import entry_points
  File "/home/vagrant/.local/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
ImportError: No module named zipp
Makefile:574: recipe for target 'virtualenv' failed
make: *** [virtualenv] Error 1
```

**Comment by RaviTezu** [comment]
Steps followed to fix the above issue:
```bash 
pip install --upgrade pip 
pip install zipp
pip install configparser
```
